<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-5FFC3DG" failures="2" tests="2" name="Default test(failed)" time="0.3" errors="0" timestamp="2023-12-11T08:18:05 IST">
  <testcase classname="test1.TestNGListenerDemo" name="test3" time="0.109">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test1.TestNGListenerDemo.test3(TestNGListenerDemo.java:28)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="test1.TestNGListenerDemo" name="test2" time="0.004">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at test1.TestNGListenerDemo.test2(TestNGListenerDemo.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="test1.TestNGListenerDemo" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
  <testcase classname="test1.TestNGListenerDemo" name="test4" time="0.0">
    <ignored/>
  </testcase> <!-- test4 -->
</testsuite> <!-- Default test(failed) -->
